stroka = input()

print(stroka[2])
print(stroka[-2])
print(stroka[0:5])
print(stroka[0:-2])
print(stroka[0::2])
print(stroka[1::2])
print(stroka[::-1])
print(stroka[-1:-stroka.__len__()-1:-2])
print(stroka.__len__())
